---
title: "Process Discovery"
output: html_document
---

```{r setup, include=FALSE}
library(here)
source(here("R/packages.r"))

knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

# Load Data
dat <- eventdataR::hospital_billing %>%
  select(case_id, activity, activity_instance_id, lifecycle, resource, timestamp)
```

# Introduction


# Everything

```{r}
process_map(dat)
```

# Traces 

```{r}
dat %>% 
  trace_explorer()

```


# Just use filters?
```{r}
dat %>%
  filter_trace_frequency(percentage = 0.95) %>%
  filter_activity_presence(
    activities = "BILLED",
    method = "one_of"
  ) %>%
  process_map()
```


# Heuristics Miner

## Defaults 
```{r}
dat %>%
  dependency_matrix() %>%
  render_dependency_matrix()
```

## Remove Self-Loops 
```{r}
dat %>%
  dependency_matrix(dependency_type = dependency_type_fhm(threshold_l1  = 1)) %>%
  render_dependency_matrix()
```


## Remove Length-Two Loops
```{r}
dat %>%
  dependency_matrix(dependency_type = dependency_type_fhm(threshold_l2 = 1)) %>%
  render_dependency_matrix()
```


## Both? 
```{r}
dat %>%
  dependency_matrix(dependency_type = dependency_type_fhm(threshold_l1 = 1, 
                                                          threshold_l2 = 1)) %>%
  render_dependency_matrix()
```

